name: go-generate
env:
  APPVERSION: v1.1.${{ github.run_number }}
on:
  workflow_dispatch: {}
  push:
    branches:
      - master
    paths:
      - '**.proto'
jobs:
  # Generate Go code from .proto files and commit to tags/golang branch and release tag
  generate-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: make docker-go
      - uses: stefanzweifel/git-auto-commit-action@v4
        id: commit
        with:
          branch: golang/${{ env.APPVERSION }}
          create_branch: true
          commit_message: "Update generated code"
      - name: GH Release
        uses: softprops/action-gh-release@v0.1.14
        with:
          tag_name: ${{ env.APPVERSION  }}
          target_commitish: ${{ steps.commit.outputs.commit_hash }}
      - name: Delete branch
        uses: dawidd6/action-delete-branch@v3.1.0
        with:
          github_token: ${{github.token}}
          branches:  golang/${{ env.APPVERSION }}

      