name: js-generate
env:
  NODE_VERSION: 18
on:
  workflow_dispatch: {}
  push:
    branches:
      - master
    paths:
      - "**.proto"

jobs:
  generate-release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: https://npm.pkg.github.com/
      - name: Add version
        run: sed -i '3s/\([0-9]\.[0-9]\)\.[0-9]\{1,10\}/\1.${{ github.run_number }}/g' package.json
      - run: npm i
      - run: npm run generate
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
